### ISSUE TITLE
Question about the diagonal elements of matrix a in _krige function

### ISSUE THREAD

**Issue by Kenichiro-Yoshimi** [mmaelicke/scikit-gstat#131]
Hello,

I have a question about the `_krige `function in the `OrdinaryKriging` class.

The [matrix `a`](https://github.com/mmaelicke/scikit-gstat/blob/7d834e6db757799ce37d0ccd1b7a6c57585116fc/skgstat/Kriging.py#L455) in the equation $a*\lambda = b$ is generated from `squareform(a)`, so the diagonal elements  are always zero, but shouldn't it supposedly match the **nugget** in the theoretical variogram?

**Comment by mmaelicke** [comment]
I guess you are right. Let me check the file history, because I thought it is implemented exactly like that, but it is not. I will try to push a PR soon. If it's urgent you are very welcome to push the PR yourself.
THanks for pointing out.

**Comment by Kenichiro-Yoshimi** [comment]
Thank you for your reply! I look forward to the fix.

**Comment by MuellerSeb** [comment]
This could be considered to be an option. in GSTools and PyKrige we provide switches called `exact` / `exact_values` to control this. Setting the diagonal to the nugget value will generate smooth results, while otherwise the calculated values will be the exact input values if evaluated at the exact input points.

This could be further used to incorporate measurement errors as described by Wackernagel (2003). See this example:
https://geostat-framework.readthedocs.io/projects/gstools/en/stable/examples/05_kriging/08_measurement_errors.html 

And last but not least, a variogram function is always `0` at the origin with a possible discontinuity there jumping to the nugget value. So in theory it is correct to have `0` on the diagonal but to get smooth results it is useful to have the limit value (i.e. the nugget):
$$\lim_{r\to 0_{+}}\gamma(r)\to n$$

**Comment by Kenichiro-Yoshimi** [comment]
@MuellerSeb
I now have a better understanding of how to control the nugget effect. Thank you very much!
