### ISSUE TITLE
Error when install package with python 3

### ISSUE THREAD

**Issue by joooseb** [mmaelicke/scikit-gstat#18]
ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\josem\AppData\Local\Temp\pip-install-pov68fqn\shapely\setup.py", line 80, in <module>
        from shapely._buildcfg import geos_version_string, geos_version, \
      File "C:\Users\josem\AppData\Local\Temp\pip-install-pov68fqn\shapely\shapely\_buildcfg.py", line 200, in <module>
        lgeos = CDLL("geos_c.dll")
      File "c:\users\josem\appdata\local\programs\python\python37-32\lib\ctypes\__init__.py", line 356, in __init__
        self._handle = _dlopen(self._name, mode)
    OSError: [WinError 126] No se puede encontrar el módulo especificado
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in C:\Users\josem\AppData\Local\Temp\pip-install-pov68fqn\shapely\

**Comment by mmaelicke** [comment]
Dear José,
Thanks for the report. 

What I can see from this error message and the translated Spanish error message, this error is not directly caused by scikit-gstat, but shapely. It's a dependency and can also be installed independently from scikit-gstat. There had been [another issue](https://github.com/mmaelicke/scikit-gstat/issues/14), in which installing shapely using conda solved it. Please have a look at it and report if the solution there is suitable for you and if it worked. 
Best,
Mirko

**Comment by joooseb** [comment]
Dear Miko,
I solved the error with the attached issue that you have posted in your comment,
thanks you so much!
and thanks too for making this great python library!
Regards,
Jose
