### ISSUE TITLE
ValueError: shape mismatch: objects cannot be broadcast to a single shape

### ISSUE THREAD

**Issue by victortm** [mmaelicke/scikit-gstat#27]
Hi again,

Im trying to plot a variogram from csv file that contains around 9000 samples. I'm passing longitude, latitude (in meters) and air pollution values to the variogram function:

```
v = Variogram(samples[['Lon','Lat']].values, samples.Data.values,normalize=False)
```
There's no problem up to this point. 

But when I want to plot the variogram:

```
fig = v.plot()
fig.savefig('variogram.png')
```

 I get the next error:

![image](https://user-images.githubusercontent.com/10722495/73838685-8c620000-4814-11ea-94b6-1fea2444c50e.png)

I've found that when I reduce the number of samples to the first 336 samples there's no error and the graph is plotted. But in the moment that I use the first 337 samples, the error appears. The only thing I've found from 337th sample is that Lon and Lat values change, but those values change on previous samples so I don't understand what's happening:

![image](https://user-images.githubusercontent.com/10722495/73839815-2aef6080-4817-11ea-9574-15eae65f7dfa.png)

Please find attached the txt file I'm working with. I recommend you to read it as follows:

```
pd.read_csv(data.txt, sep=';',decimal=',')
```

[M8data.txt](https://github.com/mmaelicke/scikit-gstat/files/4159369/M8data.txt)

Code:
```
from skgstat import Variogram
import pandas as pd
import matplotlib.pyplot as plt
from pprint import pprint
import matplotlib

plt.style.use('ggplot')
matplotlib.use('TkAgg')

data = pd.csv_read(path,sep=';',decimal=',')

samples = data.head(337) # This is the number that a I reduce/increase

v = Variogram(samples[['Lon','Lat']].values,samples.Data.values,normalize=False)

print(v)

fig = v.plot() # Line that fails
fig.savefig('variogram.png')

```

I run the code as a describe below:

```
python3 script.py
```

Thanks and best regards

**Comment by mmaelicke** [comment]
Hey,

As a quick comment: The line
```python
data = pd.csv_read(path,sep=';',decimal=',')
```

should be 
```python
data = pd.read_csv(path,sep=';',decimal=',')
```

Then, this error is connected to the histogram in the variogram plot. The problem is that these histograms can look very, very different, depending on the data you put in. Usually, this error happens if there are lags without observations (or more specifically if the last bin is empty). Usually, you can overcome this by setting another `maxlag` value. A good value is depending on your data. From which distance does a pairwise comparison of observations make no sense anymore.

Note that the `maxlag` parameter is a very important one, that should be changed every time. I just put the default value to `'mean'` as this should make a histogram possible in most cases, but as you can see: not in all cases.

To put things short: If you need the histogram, find a good partition of you data by adjusting the `n_lags` and the `maxlag` parameters. If you don't need it, or want to build it directly with numpy (that's how I do it in the class), disable the histogram in the plot:

```python
V.plot(hist=False)
```

Finally, I have a scientific remark: Without knowing your data or the analysis you are conducting, I would like to note that putting hundreds of observations from at the same location into the same dataset does not really make sense to me. I don't think that the model will show something useful and if you do that: enable the model nugget by setting 
```python
Variogram( [...], use_nugget=True)
```
The proper way to do that is space-time geostatistics. Otherwise you mix up spatial variation and the variance of the different time series. In case you want to extract a spatial model of the field underlying your measurements, you can also aggregate the data like:
```python
s2 = samples.groupby(['Lat', 'lon']).mean()
s2.reset_index(inplace=True)
V = Variogram(s2[['Lat', 'lon']].values, s2.Data.values, maxlag=0.7, normalize=False)
V.plot()
```
This will yield something like:
![test](https://user-images.githubusercontent.com/2826034/73845550-3052a800-4823-11ea-8f11-f5cbd0439b4f.png)

scikit-gstat also hast a `SpaceTimeVariogram` if you want to give that a try, but then the data has to be transformed. And please note that this class is not covered by unit tests very well and I did not use it too much.

Thanks and best

Mirko

**Comment by victortm** [comment]
Yes, what you said makes sense to me. Mixing samples from different hours and working with distances in the function, doesn't seems to work properly.

What I'm trying to do is to interpolate some air pollution data that is being collected by some stations over a delimited area. But right now I'm trying to understand all this geostatistical analysis jaja.

Thanks again for your detailed and fast response

**Comment by victortm** [comment]
You can close this issue!

**Comment by mmaelicke** [comment]
all right.

Maybe some of these resources are useful to get started:
* The [Introduction in the User Guide](https://mmaelicke.github.io/scikit-gstat/userguide/introduction.html)
* the first of the [Turotials](https://mmaelicke.github.io/scikit-gstat/tutorials/tutorials.html) I am working on at the moment.
* If you prefer someone, who knows more about geostatistics than me, there is the maybe best [Introduction into geostatistics](https://osf.io/6jzpn/download) by András Bárdossy :)

**Comment by victortm** [comment]
Thanks! :)
