### ISSUE TITLE
One point interpolation

### ISSUE THREAD

**Issue by victortm** [mmaelicke/scikit-gstat#30]
Hi,

I'm trying to interpolate just one unobserved location, passing the (x,y) coordinates to ok.transform but I'm getting the next error:

![image](https://user-images.githubusercontent.com/10722495/75965053-89683700-5ec8-11ea-9161-5b1826094ab7.png)

I thought it was failing because I wasn't passing an array (because of the len() error). But even if I create x and y independent arrays like x = np.array[xcoord] and y = np.array[ycoord], is not working:

![image](https://user-images.githubusercontent.com/10722495/75965657-67bb7f80-5ec9-11ea-92e3-31139fd0a443.png)

So if I'm understanding well, to obtain the estimations for unobserved values, you have to pass to ok.transform the locations you're interested in, right?

Is it possible to interpolate just for one location?

Thanks and best regards

**Comment by mmaelicke** [comment]
Hey again,

This might in fact be a bug. I remember implementing this was a quite dirty solution:

![image](https://user-images.githubusercontent.com/2826034/75968990-8d975300-5ece-11ea-908c-a0a40d25851d.png)

From a first view at the code, it should nevertheless be possible. Not sure yet what's going wrong. 
I will do some tests and come back to this issue. Can you post the part of your script ``gs.py``  initializing the ``x`` and ``y`` array?
Best
Mirko

**Comment by victortm** [comment]
Yes, I'm taking just the first Lon, Lat values from the samples you recommended me to group:

![image](https://user-images.githubusercontent.com/10722495/75969845-d3085000-5ecf-11ea-996e-ab691dc8ec8c.png)

```
x = np.array(s2.loc[0,'Lon'])
y = np.array(s2.loc[0,'Lat'])
```

Thanks!

**Comment by mmaelicke** [comment]
Hey,

I cannot really reproduce the error. Let me just confirm, that you are sure to be actually passing a array and not a numpy float. From your code I can see, that you are passing a float to the ``np.array`` function, because ``s2.loc[]`` will return a float.

I noticed that: 

```python
type(np.array(15))   # returns numpy.ndarray
len(np.array(15))   # raises the same error
```
This is what is happening. I can recall from somewhere (maybe numpy docs) that the proper way of creating an numpy array of length 1 is:

```python
np.array([15])

len(np.array([15])   # returns 1
```
Then, I would consider this not to be a bug, as a float and an array of only one element are two different things.

The ``OrdinaryKriging.transform`` method needs 1d arrays, therefore try to pass the arrays as created above and everything should work fine.
Can you confirm?

Thanks and best
Mirko

**Comment by victortm** [comment]
Ok, needs the [ ]. 

Now it's working, Thanks again Mirko!
